import { requireSupabase } from './client';
import { requireAdmin } from './auth';

export async function getProducts({ includeInactive = false } = {}) { if (includeInactive) await requireAdmin(); const client = requireSupabase(); let query = client.from('products').select('*, product_images(*), product_categories(category:categories(*))').order('created_at', { ascending: false }); if (!includeInactive) query = query.eq('status', 'active'); const { data, error } = await query; if (error) throw error; return data; }
export async function getProductBySlug(slug) { const { data, error } = await requireSupabase().from('products').select('*, product_images(*), product_categories(category:categories(*))').eq('slug', slug).single(); if (error) throw error; return data; }
function productWriteFields(product) { const { id, created_at, updated_at, product_categories, product_images, ...fields } = product; return fields; }
export async function createProduct(product, categoryIds = []) { await requireAdmin(); const client = requireSupabase(); const { data, error } = await client.from('products').insert(productWriteFields(product)).select().single(); if (error) throw error; if (categoryIds.length) { const { error: categoryError } = await client.from('product_categories').insert(categoryIds.map(category_id => ({ product_id: data.id, category_id }))); if (categoryError) throw categoryError; } return data; }
export async function updateProduct(id, product, categoryIds) { await requireAdmin(); const client = requireSupabase(); const { data, error } = await client.from('products').update(productWriteFields(product)).eq('id', id).select().single(); if (error) throw error; if (categoryIds) { const { error: removeError } = await client.from('product_categories').delete().eq('product_id', id); if (removeError) throw removeError; if (categoryIds.length) { const { error: categoryError } = await client.from('product_categories').insert(categoryIds.map(category_id => ({ product_id: id, category_id }))); if (categoryError) throw categoryError; } } return data; }
export async function archiveProduct(id) { return updateProduct(id, { status: 'archived' }); }
export async function deleteProduct(id) { await requireAdmin(); const { error } = await requireSupabase().from('products').delete().eq('id', id); if (error) throw error; }
export async function updateStock(id, newQuantity, reason = 'manual_adjustment') { await requireAdmin(); const client = requireSupabase(); const { data: product, error } = await client.from('products').select('stock_quantity').eq('id', id).single(); if (error) throw error; const { data: user } = await client.auth.getUser(); const { error: productError } = await client.from('products').update({ stock_quantity: newQuantity, status: newQuantity === 0 ? 'out_of_stock' : 'active' }).eq('id', id); if (productError) throw productError; const { error: movementError } = await client.from('inventory_movements').insert({ product_id: id, previous_quantity: product.stock_quantity, change_quantity: newQuantity - product.stock_quantity, new_quantity: newQuantity, reason, admin_user_id: user.user.id }); if (movementError) throw movementError; }
export async function uploadProductImage(file, productId, position = 0) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) throw new Error(`${file.name} is not a JPG, PNG, or WEBP image.`); if (file.size > 10 * 1024 * 1024) throw new Error(`${file.name} is larger than the 10 MB image limit.`); await requireAdmin(); const client = requireSupabase(); const extension = file.name.split('.').pop().toLowerCase(); const path = `${productId}/${crypto.randomUUID()}.${extension}`; const { error } = await client.storage.from('product-images').upload(path, file, { upsert: false, contentType: file.type }); if (error) throw new Error(`Could not upload ${file.name}: ${error.message}`); const { data: urlData } = client.storage.from('product-images').getPublicUrl(path); const { data, error: insertError } = await client.from('product_images').insert({ product_id: productId, storage_path: path, public_url: urlData.publicUrl, position }).select().single(); if (insertError) throw new Error(`Image uploaded, but could not attach ${file.name} to this product: ${insertError.message}`); return data; }
